version: '3.6'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: iclinic-challenge
    restart: always
    ports:
      - "3001:3001"
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
    depends_on:
      - db
    networks:
      - app

  db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - dbvolume:/var/lib/postgresql/data
    networks:
      - app

networks:
  app:

volumes:
  dbvolume:
  
